# Generated by Django 5.0 on 2023-12-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="action_choice",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("visitor", "visitor"),
                    ("creator", "creator"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
    ]
