# Generated by Django 5.0 on 2023-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_action_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="action_choice",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("visitor", "Visitor"),
                    ("creator", "Creator"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
