# Generated by Django 4.2.7 on 2023-12-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_type',
            new_name='user',
        ),
    ]
