# Generated by Django 5.0 on 2023-12-14 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Creator",
        ),
    ]
