# Generated by Django 4.2.7 on 2023-12-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_user_post_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.creator'),
        ),
    ]
